name: neural_network
description: Flutter package to simplify the use of Neural Networks
version: 0.1.0
author: Adam Fuller
homepage: https://github.com/adamfuller/neural_network

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: